---
title: "Variable educación-análisis"
author: "Camila Peña"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Librerías necesarias
```{r}
library(htmltab)
library(stringr)
library(readr) 
library(rio)
```

##Obtenemos medidas de tendencia central 

```{r}
mean(Datafinal$`Porcen-Sisabeleeryescrib`)
median(Datafinal$`Porcen-Sisabeleeryescrib`)
mode(Datafinal$`Porcen-Sisabeleeryescrib`)
```

##Sacamos un boxplot para analizar gráficamente 

```{r}
boxplot(Datafinal$`Porcen-Sisabeleeryescrib`)
```

##Correlación

```{r}
cor.test(Datafinal$`Porcen-Sisabeleeryescrib`,Datafinal$`Porc-votosV.Mendoza`)
#Si es menor a 0.05, se rechaza la HO (las variables son estadísticamente independientes).
```

summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
